name: Run tests
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  test:
    name: Legacy tests
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y shunit2
      - name: Check out branch
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          persist-credentials: false
      - name: Create the minecraft user
        run: sudo adduser --system --group --home /home/minecraft --shell /bin/bash minecraft
      - name: Run tests
        run: sudo /bin/bash ./test.sh
